image: $CI_REGISTRY/linbit/linbit-documentation

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - deploy

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  before_script:
    - echo "DEPLOY"
  script:
    - mkdir -p ~/src && cp -r . ~/src && cd ~/src && cp /linbit-documentation/GNUmakefile . && make trusthosts && make all DOCKER=n SFTPUSER=$SFTPUSER
